version: '3.4'

services:
  metahviz-front:
    image: metahviz-front
    build:
      context: Client/metah-viz
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  metahviz-server:
    image: metahviz-server
    build:
      context: ./Server
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
